@startuml
'https://plantuml.com/sequence-diagram

participant "LabyJeu"
participant "Labyrinthe"

activate LabyJeu
LabyJeu -> Labyrinthe : deplacerPerso()
activate Labyrinthe
loop caseGlacee == true
    Labyrinthe -> Labyrinthe : caseDisponible(x,y)
    Labyrinthe -> Labyrinthe : deplacerCaisse(x,y,direction)
    Labyrinthe -> Labyrinthe : etreFinis()
end
Labyrinthe --> LabyJeu :
deactivate Labyrinthe
deactivate LabyJeu

@enduml