@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant LabyJeu
participant Labyrinthe


activate LabyJeu

LabyJeu -> Labyrinthe : deplacerPerso()
activate Labyrinthe
Labyrinthe -> Labyrinthe : caseDisponible(x,y)
Labyrinthe -> Labyrinthe : deplacerCaisse(x,y,direction)
Labyrinthe --> LabyJeu :
deactivate Labyrinthe
deactivate LabyJeu



@enduml