@startuml
'https://plantuml.com/sequence-diagram
participant "jeuLab : LabyJeu " as lj
participant "laby : Labyrinthe" as l
participant "pj : Perso" as p
participant "caisses : Caisse" as c
participant "emplacementCaisses : EmplacementCaisses" as ep


autonumber

lj -> l : deplacerPerso(String action)
activate lj
activate l
l -> l : getSuivant()
l -> c : etrePresent(x,y)
activate c
l <-- c : presence: boolean
deactivate c

alt presence
    l -> l : deplacerCaisse(int x, int y, String direction)
    activate l
    l -> c : deplacer(int precedente[0], int precedente[1], int suivante[0], int suivante[1])
    activate c
    l <-- c
    deactivate c
    deactivate l
     l -> ep : etreFini(Caisse caisses)
     activate ep
     loop
     ep -> c : etrePresent(int x, int y)
     activate c
     ep <-- c : presence : true
     deactivate c
     end
     l <-- ep : finis : boolean
     deactivate ep
end
l -> c : etrePresent(x,y)
activate c
l <-- c : presence: boolean
deactivate c

alt !presence && !murs[x][y]

    l -> p : x = suivante[0]
    activate p
    l <-- p
    deactivate p
    l -> p : y = suivante[1]
    activate p
    l <-- p
    deactivate p
end

lj <-- l
deactivate l




@enduml