@startuml
'https://plantuml.com/sequence-diagram
participant "jeuLab : LabyJeu " as lj
participant "laby : Labyrinthe" as l
participant "pj : Perso" as p
participant "caisses : Caisse" as c


autonumber



activate lj
activate l
lj -> l : deplacerPerso(String action)

l -> l : getSuivant()
activate c
l -> c : etrePresent(x,y)
l <-- c : presence: boolean
alt presence
    l -> c : deplacerCaisse(int x, int y, String direction)
    l <-- c : reussi: boolean
    deactivate c
        alt reussi
            activate p
            l -> p : deplacerPerso(String action))
            l <-- p
        end
else

    l -> p : deplacerPerso(String action))
    l <-- p
    deactivate p
end

lj <-- l



@enduml