@startuml
'https://plantuml.com/sequence-diagram
participant "main" as m
participant "laby : Labyrinthe" as l
participant "pj : Perso" as p
participant "caisses : Caisse" as c
participant "emplacementCaisses : EmplacementCaisses" as ep

autonumber



activate m

m -> l : new()
activate l

l -> c : new (int x, int y)
activate c
l <-- c
deactivate c
l -> ep : new (int x, int y)
activate ep
l <-- ep
deactivate ep

l -> ep : ajouter(x,y)
activate ep
l <-- ep
deactivate ep

l -> c : ajouter(x,y)
activate c
l <-- c
deactivate c
l -> p : new(x,y)
activate p
l <-- p
deactivate p
m <-- l
deactivate l



@enduml