@startuml
'https://plantuml.com/sequence-diagram
participant "jeuLab : LabyJeu " as lj
participant "laby : Labyrinthe" as l
participant "pj : Perso" as p
participant "caisses : Caisse" as c


autonumber




lj -> l : deplacerPerso(String action)
activate lj
activate l
l -> l : getSuivant()
l -> c : etrePresent(x,y)
activate c
l <-- c : presence: boolean
deactivate c

alt presence
    l -> c : deplacerCaisse(int x, int y, String direction)
    activate c
    l <-- c : reussi: boolean
    deactivate c
        alt reussi
            l -> p : deplacerPerso(String action))
            activate p
            l <-- p
            deactivate p
        end
else

    l -> p : deplacerPerso(String action))
    activate p
    l <-- p
    deactivate p
end

lj <-- l
deactivate l



@enduml