@startuml
'https://plantuml.com/sequence-diagram

autonumber

create LabyJeu
create Labyrinthe


activate LabyJeu

LabyJeu -> Labyrinthe : deplacerPerso()
activate Labyrinthe
Labyrinthe -> Labyrinthe : caseDisponible(x,y)
Labyrinthe -> Labyrinthe : deplacerCaisse(x,y,direction)
Labyrinthe -> Labyrinthe : etreFinis()
Labyrinthe --> LabyJeu :
deactivate Labyrinthe
deactivate LabyJeu



@enduml