@startuml

class Labyrinthe{
    - murs : boolean[][]
    + Labyrinthe(nom : String)
    + getSuivant(x : int, y : int, action : String) : int[]
    + deplacerPerso(pj : Perso, direction : String)
    + deplacerCaisses(x : int, y : int, direction : String)
    + caseDisponible(x : int, y : int) : boolean
    + etreFini() : boolean
    + getLength() : int
    + getLengthY() : int
    + getMur(x : int, y : int) : boolean
    + getMurs() : boolean[][]
    + getCaisses(x : int, y : int) : boolean
    + getEmplacementsCaisse() : EmplacementsCaisse
    + getPj() : Perso
}

class Cases{
    - pos: boolean[][]
    + Cases(x : int, y : int)
    + ajouter(int : x, int : y)
    + etrePresent(int : x, int : y): boolean
    + getPos() : int
}

class Caisses {
    + Caisses(x : int, y : int)
    + deplacer(x : int, y : int, dx : int, dy : int): boolean
}

class EmplacementsCaisse {
    + EmplacementCaisses(x : int, y : int)
    + etreFini(c : Caisses): boolean
}

class Perso {
    ~ x : int
    ~ y : int
    + Perso(dx : int, dy : int)
    + etrePresent(dx : int, dy : int) : boolean
    + getX() : int
    + getY() : int
}
Labyrinthe "*" --> "1" Perso : - pj

Labyrinthe "*" --> "1" Caisses : - caisses

Labyrinthe "*" --> "1" EmplacementsCaisse : - emplacementsCaisse

Cases <|-- Caisses
Cases <|-- EmplacementsCaisse
@enduml