@startuml

class Labyrinthe{
    + murs : boolean[][]
    + getSuivant(int x, int y, String action) : int[]
    + deplacerPerso(pj : Perso, direction : String)
    + caseDisponible(x : int, y : int) : boolean
    + getLength() : int
    + getLengthY() : int
    + getMur(x : int, y : int) : boolean
}

class Positions{
    - pos: boolean[][]
    + Positions(int x, int y)
    + ajouter(int x, int y)
    + etrePresent(int x, int y): boolean
}

class Caisse {
    + Caisse()
    + deplacerCaisse(int x, int y, String direction)
}

class EmplacementCaisse {
    + EmplacementCaisse()
    + etreFini(Caisse c): boolean
}

class Perso {
    + x : int
    + y : int
    + Perso(dx: int, int dy)
    + etrePresent(dx : int, dy : int) : boolean
    + getX() : int
    + getY() : int
}
Labyrinthe "*" <-- "1" Perso : - pj

Labyrinthe "*" <-- "1" Caisse : - caisses

Labyrinthe "*" <-- "1" EmplacementCaisse : - emplacementCaisses

Positions <|-- Caisse
Positions <|-- EmplacementCaisse
@enduml